import React, { useState } from 'react'
import { Link } from 'react-router-dom'

const ACCEPTED_KEY = 'equityform:terms-accepted-v1'

export const AcceptTermsModal: React.FC = () => {
  const [accepted, setAccepted] = useState(() =>
    typeof localStorage !== 'undefined' && !!localStorage.getItem(ACCEPTED_KEY)
  )
  const [checked, setChecked] = useState(false)

  if (accepted) return null

  const handleAccept = () => {
    localStorage.setItem(ACCEPTED_KEY, new Date().toISOString())
    setAccepted(true)
  }

  return (
    <div className="accept-modal-overlay" role="dialog" aria-modal="true" aria-labelledby="accept-modal-title">
      <div className="accept-modal">
        <div className="accept-modal-header">
          <h2 id="accept-modal-title" className="accept-modal-title">Welcome to EquityForm Beta</h2>
        </div>

        <div className="accept-modal-body">
          <div className="accept-modal-scroll">
            <div className="accept-modal-section">
              <h3>Beta Software</h3>
              <p>
                EquityForm is currently in <strong>beta testing</strong>. The platform is experimental, may contain
                bugs, and is subject to change without notice. Do not use EquityForm as the sole source of truth
                for any live deal. Data may be deleted or reset during the beta period.
              </p>
            </div>

            <div className="accept-modal-section">
              <h3>Not Legal Advice</h3>
              <p>
                EquityForm does not provide legal advice. The documents generated by this platform are
                templates only and do not constitute legal counsel. No attorney-client relationship is formed
                by your use of this platform. You must have all documents reviewed by a licensed attorney
                in your state before execution.
              </p>
            </div>

            <div className="accept-modal-section">
              <h3>Not Financial Advice</h3>
              <p>
                EquityForm does not provide investment, tax, or financial advice. Economic models and
                projections are for internal planning purposes only and do not guarantee any returns.
                Consult a licensed CPA, financial advisor, and/or tax professional before making any
                financial decisions.
              </p>
            </div>

            <div className="accept-modal-section">
              <h3>Not Securities Brokerage</h3>
              <p>
                EquityForm does not offer, sell, or solicit securities. You, as the GP, are solely responsible
                for ensuring your offering complies with Regulation D and applicable state blue sky laws.
                Consult a securities attorney before accepting investor commitments.
              </p>
            </div>

            <div className="accept-modal-section">
              <h3>Data Collection</h3>
              <p>
                EquityForm stores deal data, investor PII (including tax IDs and banking information), and
                usage data. Data is scoped to your firm and is not sold to third parties. See our{' '}
                <Link to="/privacy" target="_blank" rel="noopener noreferrer" className="accept-modal-link">
                  Privacy Policy
                </Link>{' '}
                for full details.
              </p>
            </div>

            <div className="accept-modal-section">
              <p style={{ fontSize: 13, color: 'var(--color-slate-500)' }}>
                By continuing, you acknowledge these terms. Full details are in our{' '}
                <Link to="/terms" target="_blank" rel="noopener noreferrer" className="accept-modal-link">
                  Terms of Service
                </Link>{' '}
                and{' '}
                <Link to="/privacy" target="_blank" rel="noopener noreferrer" className="accept-modal-link">
                  Privacy Policy
                </Link>.
              </p>
            </div>
          </div>
        </div>

        <div className="accept-modal-footer">
          <label className="accept-modal-checkbox-row">
            <input
              type="checkbox"
              checked={checked}
              onChange={(e) => setChecked(e.target.checked)}
              className="accept-modal-checkbox"
            />
            <span>I have read and agree to the Terms of Service and Privacy Policy</span>
          </label>
          <button
            type="button"
            className="btn btn-primary"
            disabled={!checked}
            onClick={handleAccept}
          >
            Continue to EquityForm →
          </button>
        </div>
      </div>
    </div>
  )
}
