import React from 'react'
import { Link } from 'react-router-dom'

export const Terms: React.FC = () => (
  <div className="terms-page">
    <h1>Terms of Service</h1>
    <p className="legal-meta">Effective Date: June 2026 &nbsp;|&nbsp; Version 1.0 (Beta)</p>

    <div className="legal-draft-notice">
      ⚠ DRAFT — This document has not yet been reviewed by a licensed attorney. Have it reviewed
      by qualified legal counsel before beta launch or public distribution.
    </div>

    <p>
      These Terms of Service ("Terms") govern your access to and use of the EquityForm platform
      ("Platform", "we", "us"). By accessing the Platform you agree to be bound by these Terms.
      If you do not agree, do not use the Platform.
    </p>

    <h2>1. Beta Software Notice</h2>
    <p>
      EquityForm is currently in <strong>beta testing</strong>. The Platform is provided on an
      AS-IS, AS-AVAILABLE basis without warranty of any kind. It is experimental software intended
      for testing and feedback purposes only. You acknowledge that:
    </p>
    <ul>
      <li>The Platform may contain bugs, errors, or inaccuracies.</li>
      <li>Features may be added, changed, or removed without notice.</li>
      <li>Data may be deleted or reset at any time during the beta period.</li>
      <li>The Platform is not suitable for use in live, production, or executed transactions.</li>
    </ul>

    <h2>2. Not Legal Advice</h2>
    <p>
      <strong>EquityForm does not provide legal advice.</strong> Nothing on the Platform — including
      generated documents, workflow guidance, checklists, or any other content — constitutes legal
      counsel, creates an attorney-client relationship, or is a substitute for advice from a licensed
      attorney. State LLC laws, securities regulations, and tax requirements vary and change frequently.
      You must consult a licensed attorney in your jurisdiction before executing any document generated
      by the Platform.
    </p>

    <h2>3. Not Financial Advice</h2>
    <p>
      <strong>EquityForm does not provide investment, financial, or tax advice.</strong> Economic
      models, projections, waterfall analyses, and other financial outputs are for internal planning
      purposes only. They are not guarantees of returns, solicitations to invest, or professional
      financial opinions. Consult a licensed financial advisor, CPA, or tax professional before
      making any financial decision.
    </p>

    <h2>4. Not Securities Brokerage</h2>
    <p>
      EquityForm is not a registered broker-dealer, investment advisor, or securities exchange. The
      Platform does not offer, sell, or solicit the purchase of any security. You, as the General
      Partner (GP), are solely responsible for:
    </p>
    <ul>
      <li>Complying with Regulation D (Rule 506(b) or 506(c)) and applicable state blue sky laws.</li>
      <li>Filing Form D with the SEC within 15 calendar days of the first sale of securities.</li>
      <li>Verifying that all investors meet the applicable accredited investor or suitability standard.</li>
      <li>Obtaining independent securities law counsel before accepting any investor commitment.</li>
    </ul>

    <h2>5. Document Generation Disclaimer</h2>
    <p>
      Documents generated by EquityForm — including Operating Agreements, Subscription Agreements,
      K-1 Exhibits, and Closing Memos — are <strong>templates only</strong>. They are not complete,
      finalized, or jurisdiction-compliant legal documents. Specifically:
    </p>
    <ul>
      <li>Generated documents may contain placeholder values, drafting errors, or omissions.</li>
      <li>State LLC formation requirements, tax treatment, and governance rules vary by state.</li>
      <li>No generated document should be executed or relied upon without review by a licensed attorney.</li>
      <li>EquityForm is not responsible for any legal, tax, or financial consequences arising from
          the use of generated documents.</li>
    </ul>

    <h2>6. Accredited Investor Responsibility</h2>
    <p>
      EquityForm does not verify the accredited investor status of any investor entered into the
      Platform. The GP is solely responsible for conducting proper investor verification as required
      by the applicable Regulation D exemption. Failure to properly verify investors may result in
      loss of the exemption, disgorgement of proceeds, and SEC enforcement action.
    </p>

    <h2>7. Wire Transfer Disclaimer</h2>
    <p>
      EquityForm does not transmit, hold, or process any funds. Wire instructions displayed on the
      Platform are informational only. <strong>Always verify wire instructions directly with the
      receiving financial institution via a separate communication channel before initiating any
      transfer.</strong> Wire fraud is prevalent. EquityForm is not responsible for any losses
      arising from incorrect, fraudulent, or misdirected wire transfers.
    </p>

    <h2>8. Data Collection &amp; Use</h2>
    <p>
      By using the Platform you consent to the collection and use of your data as described in our{' '}
      <Link to="/privacy" className="accept-modal-link">Privacy Policy</Link>. This includes deal
      data, investor PII (names, addresses, tax IDs), financial information, and usage data. We do
      not sell your personal data to third parties.
    </p>

    <h2>9. Limitation of Liability</h2>
    <p>
      TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, EQUITYFORM AND ITS OFFICERS, EMPLOYEES,
      AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
      PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE PLATFORM, INCLUDING BUT NOT LIMITED TO LOSS OF
      PROFITS, DATA, OR BUSINESS OPPORTUNITY. IN NO EVENT SHALL OUR TOTAL LIABILITY EXCEED THE
      GREATER OF (A) THE SUBSCRIPTION FEES YOU PAID IN THE 12 MONTHS PRECEDING THE CLAIM, OR (B)
      ONE HUNDRED U.S. DOLLARS ($100).
    </p>

    <h2>10. Indemnification</h2>
    <p>
      You agree to indemnify, defend, and hold harmless EquityForm and its affiliates from any
      claims, damages, liabilities, costs, and expenses (including reasonable attorneys' fees)
      arising from: (a) your use of the Platform; (b) any document you generate, execute, or
      distribute using the Platform; (c) your offering of securities to investors; or (d) your
      violation of these Terms or applicable law.
    </p>

    <h2>11. Intellectual Property</h2>
    <p>
      The Platform, including its templates, workflows, code, and design, is the intellectual
      property of EquityForm. Generated documents are licensed to you for use solely in connection
      with the named SPV for which they were generated. Templates and underlying document structures
      remain the property of EquityForm.
    </p>

    <h2>12. Governing Law &amp; Dispute Resolution</h2>
    <p>
      These Terms are governed by the laws of the State of Delaware without regard to conflict of
      law principles. Any dispute arising from these Terms shall be resolved by binding arbitration
      under the rules of the American Arbitration Association, conducted in Delaware. You waive any
      right to participate in a class action lawsuit or class-wide arbitration.
    </p>

    <h2>13. Contact</h2>
    <p>
      Questions about these Terms? Contact us at{' '}
      <a href="mailto:support@equityform.com" className="accept-modal-link">support@equityform.com</a>.
    </p>

    <p style={{ marginTop: 40, fontSize: 12, color: 'var(--color-slate-400)' }}>
      © {new Date().getFullYear()} EquityForm. All rights reserved.
    </p>
  </div>
)
