import React, { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import {
  useEconomicsStore,
  canLockEconomics,
  isEconomicsLocked,
} from '../../../state/economicsStore'
import {
  validateSectionA,
  validateSectionB,
  validateSectionC,
} from '../../../utils/economicsValidation'
import { SectionA } from './SectionA'
import { SectionB } from './SectionB'
import { SectionC } from './SectionC'

type Tab = 'A' | 'B' | 'C'

const TABS: { id: Tab; label: string; sub: string }[] = [
  { id: 'A', label: 'Capital Stack',  sub: 'Purchase, debt & leverage'  },
  { id: 'B', label: 'Profit Split',   sub: 'Pref return & waterfall'     },
  { id: 'C', label: 'Fees',           sub: 'Acquisition, AM & other'     },
]

export const Economics: React.FC = () => {
  const { dealId }  = useParams<{ dealId: string }>()
  const [tab, setTab] = useState<Tab>('A')
  const navigate = useNavigate()

  const getOrCreateDeal = useEconomicsStore(s => s.getOrCreateDeal)
  const lockEconomics   = useEconomicsStore(s => s.lockEconomics)
  const unlockEconomics = useEconomicsStore(s => s.unlockEconomics)
  const deal = useEconomicsStore(s => s.deals.find(d => d.dealId === dealId))

  // Seed deal on first mount
  useEffect(() => { if (dealId) getOrCreateDeal(dealId) }, [dealId]) // eslint-disable-line react-hooks/exhaustive-deps

  if (!deal) return null

  const doneA = deal.sectionAComplete
  const doneB = deal.sectionBComplete
  const doneC = deal.sectionCComplete

  // Live error counts drive the "needs attention" indicator even before explicit complete
  const errCountA = validateSectionA(deal).length
  const errCountB = validateSectionB(deal).length
  const errCountC = validateSectionC(deal).length

  const locked  = isEconomicsLocked(deal)
  const canLock = canLockEconomics(deal)

  // Pre-compute so TypeScript doesn't lose narrowing inside the closure
  const hasPurchasePrice = !!deal.capitalStack?.purchasePrice
  const hasFeeAnswers    = deal.fees.some(f => f.enabled !== null)

  function tabDotClass(t: Tab, done: boolean, active: boolean, errCount: number): string {
    if (done)   return 'econ-tab-dot econ-tab-dot--done'
    if (active) return 'econ-tab-dot econ-tab-dot--active'
    if (errCount === 0 && t === 'A' && hasPurchasePrice) return 'econ-tab-dot econ-tab-dot--valid'
    if (errCount === 0 && t === 'C' && hasFeeAnswers)    return 'econ-tab-dot econ-tab-dot--valid'
    return 'econ-tab-dot'
  }

  return (
    <div className="econ-root">

      {/* ── Header ── */}
      <div className="page-header">
        <div>
          <h1>Deal Economics</h1>
          <p className="page-subtitle">Capital structure, profit split &amp; fee schedule</p>
        </div>
        {locked && (
          <span className="econ-locked-badge" aria-label="Economics locked">
            <span aria-hidden="true">🔒</span> Locked
          </span>
        )}
      </div>

      {/* Financial projections notice */}
      <div className="disclaimer-banner disclaimer-banner--info" style={{ marginBottom: 16 }}>
        <span className="disclaimer-banner-icon">ℹ</span>
        <div className="disclaimer-banner-body">
          <strong>Financial Projections Notice</strong>
          <p>
            Economic models and projections generated by EquityForm are for internal planning
            purposes only. They do not constitute investment advice, a guarantee of returns, or
            a solicitation to invest. All projections involve assumptions that may not reflect
            actual outcomes.
          </p>
        </div>
      </div>

      {/* ── Section tabs ── */}
      <div className="econ-tabs" role="tablist" aria-label="Economics sections">
        {TABS.map(t => {
          const active = tab === t.id
          const done   = t.id === 'A' ? doneA : t.id === 'B' ? doneB : doneC
          const errs   = t.id === 'A' ? errCountA : t.id === 'B' ? errCountB : errCountC
          return (
            <button
              key={t.id}
              role="tab"
              type="button"
              aria-selected={active}
              className={['econ-tab', active ? 'econ-tab--active' : ''].filter(Boolean).join(' ')}
              onClick={() => setTab(t.id)}
            >
              <span className={tabDotClass(t.id, done, active, errs)} aria-hidden="true">
                {done ? '✓' : t.id}
              </span>
              <span className="econ-tab-info">
                <span className="econ-tab-label">{t.label}</span>
                <span className="econ-tab-sub">{t.sub}</span>
              </span>
            </button>
          )
        })}
      </div>

      {/* ── Active section ── */}
      <div className="econ-body">
        {tab === 'A' && <SectionA dealId={dealId!} locked={locked} setTab={setTab} />}
        {tab === 'B' && <SectionB dealId={dealId!} locked={locked} setTab={setTab} />}
        {tab === 'C' && <SectionC dealId={dealId!} locked={locked} />}
      </div>

      {/* ── Lock / Unlock bar ── */}
      {locked ? (
        <div className="econ-lock-bar econ-lock-bar--locked">
          <div className="econ-lock-bar-inner">
            <div className="econ-lock-bar-msg">
              <strong>Economics locked</strong>
              <span>
                Locked{' '}
                {new Date(deal.lockedAt!).toLocaleDateString('en-US', {
                  month: 'short', day: 'numeric', year: 'numeric',
                })}
              </span>
            </div>
            <button
              type="button"
              className="btn btn-secondary btn-sm"
              onClick={() => unlockEconomics(dealId!, 'Manual unlock')}
            >
              Unlock
            </button>
          </div>
        </div>
      ) : canLock ? (
        <div className="econ-lock-bar econ-lock-bar--ready">
          <div className="econ-lock-bar-inner">
            <div className="econ-lock-bar-msg">
              <strong>All sections complete</strong>
              <span>Lock the economics to proceed to SPV formation.</span>
            </div>
            <button
              type="button"
              className="btn btn-primary"
              onClick={() => { lockEconomics(dealId!, 'GP'); navigate(`/deals/${dealId}/spv`) }}
            >
              Lock Economics
            </button>
          </div>
        </div>
      ) : null}

    </div>
  )
}
