import type { ImportFieldRule } from '../../types/importTypes'

export const importFieldRules: ImportFieldRule[] = [
  {
    fieldKey: 'grossPotentialRent',
    aliases: ['Gross Potential Rent', 'GPR', 'Gross Potential Rent (GPR)'],
    sheetHints: ['P&L', 'Income'],
    sectionHints: ['Revenue', 'Income'],
    type: 'number',
  },
  {
    fieldKey: 'vacancyLoss',
    aliases: ['Vacancy Loss', 'Vacancy', 'Vacancy & Credit Loss'],
    sheetHints: ['P&L', 'Income'],
    sectionHints: ['Revenue', 'Income'],
    type: 'number',
  },
  {
    fieldKey: 'concessions',
    aliases: ['Concessions', 'Rent Concessions'],
    sheetHints: ['P&L'],
    sectionHints: ['Revenue', 'Income'],
    type: 'number',
  },
  {
    fieldKey: 'badDebt',
    aliases: ['Bad Debt', 'Bad Debt & Credit Loss'],
    sheetHints: ['P&L'],
    sectionHints: ['Revenue', 'Income'],
    type: 'number',
  },
  {
    fieldKey: 'utilityReimbursements',
    aliases: ['Utility Reimbursements', 'RUBS', 'Utility Reimbursement'],
    sheetHints: ['P&L'],
    sectionHints: ['Revenue', 'Income'],
    type: 'number',
  },
  {
    fieldKey: 'otherIncome',
    aliases: ['Other Income', 'Misc Income', 'Other Revenue'],
    sheetHints: ['P&L'],
    sectionHints: ['Revenue', 'Income'],
    type: 'number',
  },
  {
    fieldKey: 'propertyManagementFee',
    aliases: ['Property Management Fee', 'Management Fee'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'payrollBenefits',
    aliases: ['Payroll & Benefits', 'Payroll', 'Salaries & Benefits'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'repairsMaintenance',
    aliases: ['Repairs & Maintenance', 'Repairs and Maintenance', 'R&M'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'makeReadyTurns',
    aliases: ['Make-Ready', 'Unit Turns', 'Make Ready'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'landscaping',
    aliases: ['Landscaping', 'Grounds', 'Landscaping & Grounds'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'utilitiesCommonArea',
    aliases: ['Utilities - Common Area', 'Utilities Common Area', 'Common Area Utilities'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'insurance',
    aliases: ['Insurance', 'Property Insurance'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'propertyTaxes',
    aliases: ['Property Taxes', 'Real Estate Taxes', 'Taxes'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'marketingAdvertising',
    aliases: ['Marketing & Advertising', 'Marketing', 'Advertising'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'administrativeGeneral',
    aliases: ['Administrative & General', 'Admin & General', 'General & Administrative'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'contractServices',
    aliases: ['Contract Services', 'Professional Services'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'totalRentableUnits',
    aliases: ['Total Rentable Units', 'Total Units', 'Units'],
    sheetHints: ['P&L', 'Stats'],
    sectionHints: ['Property Statistics', 'Stats'],
    type: 'number',
  },
  {
    fieldKey: 'occupiedUnits',
    aliases: ['Occupied Units', 'Occupied'],
    sheetHints: ['P&L', 'Stats'],
    sectionHints: ['Property Statistics', 'Stats'],
    type: 'number',
  },
  {
    fieldKey: 'avgRent',
    aliases: ['Average Rent', 'Avg Rent', 'Average Rent ($/unit/mo)'],
    sheetHints: ['P&L', 'Stats'],
    sectionHints: ['Property Statistics', 'Stats'],
    type: 'number',
  },
  {
    fieldKey: 'depreciation',
    aliases: ['Depreciation', 'Depreciation (straight-line)', 'Depreciation and Amortization'],
    sheetHints: ['Below', 'Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Depreciation', 'Amortization', 'Operating', 'Adjustments'],
    type: 'number',
  },
  {
    fieldKey: 'amortizationFinancingCosts',
    aliases: ['Amortization of Deferred Financing Costs', 'Financing Cost Amortization'],
    sheetHints: ['Below', 'Cash Flow'],
    sectionHints: ['Depreciation', 'Amortization'],
    type: 'number',
  },
  {
    fieldKey: 'debtServiceInterest',
    aliases: ['Debt Service Interest', 'Interest', 'Loan Interest'],
    sheetHints: ['Below', 'Debt'],
    sectionHints: ['Debt Service', 'Debt'],
    type: 'number',
  },
  {
    fieldKey: 'debtServicePrincipal',
    aliases: ['Debt Service Principal', 'Principal', 'Loan Principal'],
    sheetHints: ['Below', 'Debt'],
    sectionHints: ['Debt Service', 'Debt'],
    type: 'number',
  },
  {
    fieldKey: 'capEx',
    aliases: ['CapEx', 'Capital Expenditures', 'Capital Expenditure'],
    sheetHints: ['Below', 'Cash Flow'],
    sectionHints: ['CapEx', 'Reserves'],
    type: 'number',
  },
  {
    fieldKey: 'replacementReserve',
    aliases: ['Replacement Reserve', 'Reserve', 'Reserves'],
    sheetHints: ['Below', 'Cash Flow'],
    sectionHints: ['CapEx', 'Reserves'],
    type: 'number',
  },
  {
    fieldKey: 'depreciationOverridden',
    aliases: ['Depreciation Override', 'Depreciation Overridden'],
    sheetHints: ['Below'],
    sectionHints: ['Depreciation'],
    type: 'boolean',
  },
  {
    fieldKey: 'debtServiceOverridden',
    aliases: ['Debt Service Override', 'Debt Service Overridden'],
    sheetHints: ['Below'],
    sectionHints: ['Debt Service'],
    type: 'boolean',
  },
  {
    fieldKey: 'capExOverridden',
    aliases: ['CapEx Override', 'CapEx Overridden'],
    sheetHints: ['Below'],
    sectionHints: ['CapEx'],
    type: 'boolean',
  },
  {
    fieldKey: 'changeInAccountsReceivable',
    aliases: ['Change in Accounts Receivable', 'Change in AR', 'Accounts Receivable Change'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Operating'],
    type: 'number',
  },
  {
    fieldKey: 'changeInPrepaidExpenses',
    aliases: ['Change in Prepaid Expenses', 'Change in Prepaids'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Operating'],
    type: 'number',
  },
  {
    fieldKey: 'changeInAccountsPayable',
    aliases: ['Change in Accounts Payable', 'Change in AP'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Operating'],
    type: 'number',
  },
  {
    fieldKey: 'changeInAccruedLiabilities',
    aliases: ['Change in Accrued Liabilities', 'Change in Accruals'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Operating'],
    type: 'number',
  },
  {
    fieldKey: 'changeInSecurityDeposits',
    aliases: ['Change in Security Deposits', 'Security Deposits'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Operating'],
    type: 'number',
  },
  {
    fieldKey: 'otherOperatingAdjustments',
    aliases: ['Other Operating Adjustments', 'Other Operating Changes'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Operating'],
    type: 'number',
  },
  {
    fieldKey: 'proceedsFromSaleOfAssets',
    aliases: ['Proceeds from Sale of Assets', 'Sale of Assets'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Investing'],
    type: 'number',
  },
  {
    fieldKey: 'otherInvestingActivities',
    aliases: ['Other Investing Activities', 'Other Investing'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Investing'],
    type: 'number',
  },
  {
    fieldKey: 'proceedsFromNewBorrowings',
    aliases: ['Proceeds from New Borrowings', 'New Borrowings'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Financing'],
    type: 'number',
  },
  {
    fieldKey: 'capitalContributions',
    aliases: ['Capital Contributions', 'Contributions'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Financing'],
    type: 'number',
  },
  {
    fieldKey: 'otherFinancingActivities',
    aliases: ['Other Financing Activities', 'Other Financing'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Financing'],
    type: 'number',
  },
  {
    fieldKey: 'netIncome',
    aliases: ['Net Income', 'Net Income (Loss)', 'Net Income Per Books'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Operating'],
    type: 'number',
  },
  {
    fieldKey: 'amortization',
    aliases: ['Amortization', 'Amortization Expense'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Operating', 'Adjustments'],
    type: 'number',
  },
  {
    fieldKey: 'deferredTax',
    aliases: ['Deferred Tax', 'Deferred Taxes'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Operating', 'Adjustments'],
    type: 'number',
  },
  {
    fieldKey: 'gainLossOnSale',
    aliases: ['Gain/Loss on Sale', 'Gain on Sale', 'Loss on Sale'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Operating', 'Adjustments'],
    type: 'number',
  },
  {
    fieldKey: 'accountsReceivableChange',
    aliases: ['Accounts Receivable Change', 'Change in Accounts Receivable', 'AR Change'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Operating', 'Working Capital'],
    type: 'number',
  },
  {
    fieldKey: 'inventoryChange',
    aliases: ['Inventory Change', 'Change in Inventory'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Operating', 'Working Capital'],
    type: 'number',
  },
  {
    fieldKey: 'prepaidExpensesChange',
    aliases: ['Prepaid Expenses Change', 'Change in Prepaid Expenses'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Operating', 'Working Capital'],
    type: 'number',
  },
  {
    fieldKey: 'accountsPayableChange',
    aliases: ['Accounts Payable Change', 'Change in Accounts Payable', 'AP Change'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Operating', 'Working Capital'],
    type: 'number',
  },
  {
    fieldKey: 'accruedExpensesChange',
    aliases: ['Accrued Expenses Change', 'Change in Accrued Expenses'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Operating', 'Working Capital'],
    type: 'number',
  },
  {
    fieldKey: 'netCashFromOperations',
    aliases: ['Net Cash from Operations', 'Net Cash Provided by Operating Activities'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Operating'],
    type: 'number',
  },
  {
    fieldKey: 'capitalExpenditures',
    aliases: ['Capital Expenditures', 'CapEx'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Investing'],
    type: 'number',
  },
  {
    fieldKey: 'propertyPurchase',
    aliases: ['Property Purchase', 'Purchase of Property', 'Acquisition of Property'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Investing'],
    type: 'number',
  },
  {
    fieldKey: 'propertySale',
    aliases: ['Property Sale', 'Sale of Property'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Investing'],
    type: 'number',
  },
  {
    fieldKey: 'investmentPurchase',
    aliases: ['Investment Purchase', 'Purchase of Investments'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Investing'],
    type: 'number',
  },
  {
    fieldKey: 'investmentSale',
    aliases: ['Investment Sale', 'Sale of Investments'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Investing'],
    type: 'number',
  },
  {
    fieldKey: 'netCashFromInvesting',
    aliases: ['Net Cash from Investing', 'Net Cash Used in Investing Activities'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Investing'],
    type: 'number',
  },
  {
    fieldKey: 'debtProceeds',
    aliases: ['Debt Proceeds', 'Loan Proceeds', 'Borrowings'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Financing'],
    type: 'number',
  },
  {
    fieldKey: 'debtRepayment',
    aliases: ['Debt Repayment', 'Loan Repayment', 'Principal Repayment'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Financing'],
    type: 'number',
  },
  {
    fieldKey: 'equityContributions',
    aliases: ['Equity Contributions', 'Capital Contributions'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Financing'],
    type: 'number',
  },
  {
    fieldKey: 'dividendsDistributions',
    aliases: ['Dividends', 'Distributions', 'Dividends/Distributions'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Financing'],
    type: 'number',
  },
  {
    fieldKey: 'netCashFromFinancing',
    aliases: ['Net Cash from Financing', 'Net Cash Provided by Financing Activities'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Financing'],
    type: 'number',
  },
  {
    fieldKey: 'netChangeInCash',
    aliases: ['Net Change in Cash', 'Net Increase (Decrease) in Cash'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Totals', 'Reconciliation'],
    type: 'number',
  },
  {
    fieldKey: 'cashBeginning',
    aliases: ['Beginning Cash', 'Cash Beginning', 'Cash — Beginning'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Totals', 'Reconciliation'],
    type: 'number',
  },
  {
    fieldKey: 'cashEnding',
    aliases: ['Ending Cash', 'Cash Ending', 'Cash — Ending'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Totals', 'Reconciliation'],
    type: 'number',
  },
  {
    fieldKey: 'interestPaidDisclosure',
    aliases: ['Interest Paid', 'Cash Paid for Interest'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Supplemental', 'Disclosures'],
    type: 'number',
  },
  {
    fieldKey: 'taxesPaidDisclosure',
    aliases: ['Taxes Paid', 'Cash Paid for Income Taxes'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Supplemental', 'Disclosures'],
    type: 'number',
  },
  {
    fieldKey: 'nonCashInvestingFinancing',
    aliases: ['Non-Cash Investing & Financing Activities', 'Non-Cash Activities'],
    sheetHints: ['Cash Flow', 'Statement of Cash Flows'],
    sectionHints: ['Supplemental', 'Disclosures'],
    type: 'number',
  },
  {
    fieldKey: 'actualLPDistribution',
    aliases: ['Actual LP Distribution', 'LP Distribution', 'LP Distributions'],
    sheetHints: ['Distributions', 'Cash Flow'],
    sectionHints: ['Distributions'],
    type: 'number',
  },
  {
    fieldKey: 'actualGPDistribution',
    aliases: ['Actual GP Distribution', 'GP Distribution', 'GP Distributions'],
    sheetHints: ['Distributions', 'Cash Flow'],
    sectionHints: ['Distributions'],
    type: 'number',
  },
  {
    fieldKey: 'isOverridden',
    aliases: ['Distribution Override', 'Override Distribution'],
    sheetHints: ['Distributions'],
    sectionHints: ['Distributions'],
    type: 'boolean',
  },
  {
    fieldKey: 'overrideNote',
    aliases: ['Override Note', 'Distribution Note', 'Override Reason'],
    sheetHints: ['Distributions'],
    sectionHints: ['Distributions'],
    type: 'string',
  },
  {
    fieldKey: 'notes',
    aliases: ['Notes', 'Comments', 'Memo'],
    sheetHints: ['Notes'],
    type: 'string',
  },
]

export const fieldLabelMap: Record<string, string> = {
  grossPotentialRent: 'Gross Potential Rent (GPR)',
  vacancyLoss: 'Vacancy Loss',
  concessions: 'Concessions',
  badDebt: 'Bad Debt & Credit Loss',
  utilityReimbursements: 'Utility Reimbursements',
  otherIncome: 'Other Income',
  propertyManagementFee: 'Property Management Fee',
  payrollBenefits: 'Payroll & Benefits',
  repairsMaintenance: 'Repairs & Maintenance',
  makeReadyTurns: 'Make-Ready / Unit Turns',
  landscaping: 'Landscaping & Grounds',
  utilitiesCommonArea: 'Utilities — Common Area',
  insurance: 'Insurance',
  propertyTaxes: 'Property Taxes',
  marketingAdvertising: 'Marketing & Advertising',
  administrativeGeneral: 'Administrative & General',
  contractServices: 'Contract Services',
  totalRentableUnits: 'Total Rentable Units',
  occupiedUnits: 'Occupied Units',
  avgRent: 'Average Rent ($/unit/mo)',
  amortizationFinancingCosts: 'Amortization of Deferred Financing Costs',
  debtServiceInterest: 'Debt Service Interest',
  debtServicePrincipal: 'Debt Service Principal',
  capEx: 'Capital Expenditures (CapEx)',
  replacementReserve: 'Replacement Reserve',
  depreciationOverridden: 'Depreciation Overridden',
  debtServiceOverridden: 'Debt Service Overridden',
  capExOverridden: 'CapEx Overridden',
  changeInAccountsReceivable: 'Change in Accounts Receivable',
  changeInPrepaidExpenses: 'Change in Prepaid Expenses',
  changeInAccountsPayable: 'Change in Accounts Payable',
  changeInAccruedLiabilities: 'Change in Accrued Liabilities',
  changeInSecurityDeposits: 'Change in Security Deposits',
  otherOperatingAdjustments: 'Other Operating Adjustments',
  proceedsFromSaleOfAssets: 'Proceeds from Sale of Assets',
  otherInvestingActivities: 'Other Investing Activities',
  proceedsFromNewBorrowings: 'Proceeds from New Borrowings',
  capitalContributions: 'Capital Contributions',
  otherFinancingActivities: 'Other Financing Activities',
  netIncome: 'Net Income',
  depreciation: 'Depreciation',
  amortization: 'Amortization',
  deferredTax: 'Deferred Tax',
  gainLossOnSale: 'Gain / (Loss) on Sale of Assets',
  accountsReceivableChange: 'Accounts Receivable Change',
  inventoryChange: 'Inventory Change',
  prepaidExpensesChange: 'Prepaid Expenses Change',
  accountsPayableChange: 'Accounts Payable Change',
  accruedExpensesChange: 'Accrued Expenses Change',
  netCashFromOperations: 'Net Cash from Operations',
  capitalExpenditures: 'Capital Expenditures',
  propertyPurchase: 'Property Purchase',
  propertySale: 'Property Sale',
  investmentPurchase: 'Investment Purchase',
  investmentSale: 'Investment Sale',
  netCashFromInvesting: 'Net Cash from Investing',
  debtProceeds: 'Debt Proceeds',
  debtRepayment: 'Debt Repayment',
  equityContributions: 'Equity Contributions',
  dividendsDistributions: 'Dividends / Distributions',
  netCashFromFinancing: 'Net Cash from Financing',
  netChangeInCash: 'Net Change in Cash',
  cashBeginning: 'Cash Beginning',
  cashEnding: 'Cash Ending',
  interestPaidDisclosure: 'Cash Paid for Interest',
  taxesPaidDisclosure: 'Cash Paid for Income Taxes',
  nonCashInvestingFinancing: 'Non-Cash Investing & Financing Activities',
  actualLPDistribution: 'Actual LP Distribution',
  actualGPDistribution: 'Actual GP Distribution',
  isOverridden: 'Distribution Override',
  overrideNote: 'Override Note',
  notes: 'Notes',
}