import type { ImportFieldRule } from '../../types/importTypes'

export const importFieldRules: ImportFieldRule[] = [
  {
    fieldKey: 'grossPotentialRent',
    aliases: ['Gross Potential Rent', 'GPR', 'Gross Potential Rent (GPR)'],
    sheetHints: ['P&L', 'Income'],
    sectionHints: ['Revenue', 'Income'],
    type: 'number',
  },
  {
    fieldKey: 'vacancyLoss',
    aliases: ['Vacancy Loss', 'Vacancy', 'Vacancy & Credit Loss'],
    sheetHints: ['P&L', 'Income'],
    sectionHints: ['Revenue', 'Income'],
    type: 'number',
  },
  {
    fieldKey: 'concessions',
    aliases: ['Concessions', 'Rent Concessions'],
    sheetHints: ['P&L'],
    sectionHints: ['Revenue', 'Income'],
    type: 'number',
  },
  {
    fieldKey: 'badDebt',
    aliases: ['Bad Debt', 'Bad Debt & Credit Loss'],
    sheetHints: ['P&L'],
    sectionHints: ['Revenue', 'Income'],
    type: 'number',
  },
  {
    fieldKey: 'utilityReimbursements',
    aliases: ['Utility Reimbursements', 'RUBS', 'Utility Reimbursement'],
    sheetHints: ['P&L'],
    sectionHints: ['Revenue', 'Income'],
    type: 'number',
  },
  {
    fieldKey: 'otherIncome',
    aliases: ['Other Income', 'Misc Income', 'Other Revenue'],
    sheetHints: ['P&L'],
    sectionHints: ['Revenue', 'Income'],
    type: 'number',
  },
  {
    fieldKey: 'propertyManagementFee',
    aliases: ['Property Management Fee', 'Management Fee'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'payrollBenefits',
    aliases: ['Payroll & Benefits', 'Payroll', 'Salaries & Benefits'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'repairsMaintenance',
    aliases: ['Repairs & Maintenance', 'Repairs and Maintenance', 'R&M'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'makeReadyTurns',
    aliases: ['Make-Ready', 'Unit Turns', 'Make Ready'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'landscaping',
    aliases: ['Landscaping', 'Grounds', 'Landscaping & Grounds'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'utilitiesCommonArea',
    aliases: ['Utilities - Common Area', 'Utilities Common Area', 'Common Area Utilities'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'insurance',
    aliases: ['Insurance', 'Property Insurance'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'propertyTaxes',
    aliases: ['Property Taxes', 'Real Estate Taxes', 'Taxes'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'marketingAdvertising',
    aliases: ['Marketing & Advertising', 'Marketing', 'Advertising'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'administrativeGeneral',
    aliases: ['Administrative & General', 'Admin & General', 'General & Administrative'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'contractServices',
    aliases: ['Contract Services', 'Professional Services'],
    sheetHints: ['P&L', 'Expenses'],
    sectionHints: ['Operating Expenses', 'Expenses'],
    type: 'number',
  },
  {
    fieldKey: 'totalRentableUnits',
    aliases: ['Total Rentable Units', 'Total Units', 'Units'],
    sheetHints: ['P&L', 'Stats'],
    sectionHints: ['Property Statistics', 'Stats'],
    type: 'number',
  },
  {
    fieldKey: 'occupiedUnits',
    aliases: ['Occupied Units', 'Occupied'],
    sheetHints: ['P&L', 'Stats'],
    sectionHints: ['Property Statistics', 'Stats'],
    type: 'number',
  },
  {
    fieldKey: 'avgRent',
    aliases: ['Average Rent', 'Avg Rent', 'Average Rent ($/unit/mo)'],
    sheetHints: ['P&L', 'Stats'],
    sectionHints: ['Property Statistics', 'Stats'],
    type: 'number',
  },
  {
    fieldKey: 'depreciation',
    aliases: ['Depreciation', 'Depreciation (straight-line)'],
    sheetHints: ['Below', 'Cash Flow'],
    sectionHints: ['Depreciation', 'Amortization'],
    type: 'number',
  },
  {
    fieldKey: 'amortizationFinancingCosts',
    aliases: ['Amortization of Deferred Financing Costs', 'Financing Cost Amortization'],
    sheetHints: ['Below', 'Cash Flow'],
    sectionHints: ['Depreciation', 'Amortization'],
    type: 'number',
  },
  {
    fieldKey: 'debtServiceInterest',
    aliases: ['Debt Service Interest', 'Interest', 'Loan Interest'],
    sheetHints: ['Below', 'Debt'],
    sectionHints: ['Debt Service', 'Debt'],
    type: 'number',
  },
  {
    fieldKey: 'debtServicePrincipal',
    aliases: ['Debt Service Principal', 'Principal', 'Loan Principal'],
    sheetHints: ['Below', 'Debt'],
    sectionHints: ['Debt Service', 'Debt'],
    type: 'number',
  },
  {
    fieldKey: 'capEx',
    aliases: ['CapEx', 'Capital Expenditures', 'Capital Expenditure'],
    sheetHints: ['Below', 'Cash Flow'],
    sectionHints: ['CapEx', 'Reserves'],
    type: 'number',
  },
  {
    fieldKey: 'replacementReserve',
    aliases: ['Replacement Reserve', 'Reserve', 'Reserves'],
    sheetHints: ['Below', 'Cash Flow'],
    sectionHints: ['CapEx', 'Reserves'],
    type: 'number',
  },
  {
    fieldKey: 'depreciationOverridden',
    aliases: ['Depreciation Override', 'Depreciation Overridden'],
    sheetHints: ['Below'],
    sectionHints: ['Depreciation'],
    type: 'boolean',
  },
  {
    fieldKey: 'debtServiceOverridden',
    aliases: ['Debt Service Override', 'Debt Service Overridden'],
    sheetHints: ['Below'],
    sectionHints: ['Debt Service'],
    type: 'boolean',
  },
  {
    fieldKey: 'capExOverridden',
    aliases: ['CapEx Override', 'CapEx Overridden'],
    sheetHints: ['Below'],
    sectionHints: ['CapEx'],
    type: 'boolean',
  },
  {
    fieldKey: 'changeInAccountsReceivable',
    aliases: ['Change in Accounts Receivable', 'Change in AR', 'Accounts Receivable Change'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Operating'],
    type: 'number',
  },
  {
    fieldKey: 'changeInPrepaidExpenses',
    aliases: ['Change in Prepaid Expenses', 'Change in Prepaids'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Operating'],
    type: 'number',
  },
  {
    fieldKey: 'changeInAccountsPayable',
    aliases: ['Change in Accounts Payable', 'Change in AP'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Operating'],
    type: 'number',
  },
  {
    fieldKey: 'changeInAccruedLiabilities',
    aliases: ['Change in Accrued Liabilities', 'Change in Accruals'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Operating'],
    type: 'number',
  },
  {
    fieldKey: 'changeInSecurityDeposits',
    aliases: ['Change in Security Deposits', 'Security Deposits'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Operating'],
    type: 'number',
  },
  {
    fieldKey: 'otherOperatingAdjustments',
    aliases: ['Other Operating Adjustments', 'Other Operating Changes'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Operating'],
    type: 'number',
  },
  {
    fieldKey: 'proceedsFromSaleOfAssets',
    aliases: ['Proceeds from Sale of Assets', 'Sale of Assets'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Investing'],
    type: 'number',
  },
  {
    fieldKey: 'otherInvestingActivities',
    aliases: ['Other Investing Activities', 'Other Investing'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Investing'],
    type: 'number',
  },
  {
    fieldKey: 'proceedsFromNewBorrowings',
    aliases: ['Proceeds from New Borrowings', 'New Borrowings'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Financing'],
    type: 'number',
  },
  {
    fieldKey: 'capitalContributions',
    aliases: ['Capital Contributions', 'Contributions'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Financing'],
    type: 'number',
  },
  {
    fieldKey: 'otherFinancingActivities',
    aliases: ['Other Financing Activities', 'Other Financing'],
    sheetHints: ['Working Capital', 'Cash Flow'],
    sectionHints: ['Financing'],
    type: 'number',
  },
  {
    fieldKey: 'actualLPDistribution',
    aliases: ['Actual LP Distribution', 'LP Distribution', 'LP Distributions'],
    sheetHints: ['Distributions', 'Cash Flow'],
    sectionHints: ['Distributions'],
    type: 'number',
  },
  {
    fieldKey: 'actualGPDistribution',
    aliases: ['Actual GP Distribution', 'GP Distribution', 'GP Distributions'],
    sheetHints: ['Distributions', 'Cash Flow'],
    sectionHints: ['Distributions'],
    type: 'number',
  },
  {
    fieldKey: 'isOverridden',
    aliases: ['Distribution Override', 'Override Distribution'],
    sheetHints: ['Distributions'],
    sectionHints: ['Distributions'],
    type: 'boolean',
  },
  {
    fieldKey: 'overrideNote',
    aliases: ['Override Note', 'Distribution Note', 'Override Reason'],
    sheetHints: ['Distributions'],
    sectionHints: ['Distributions'],
    type: 'string',
  },
  {
    fieldKey: 'notes',
    aliases: ['Notes', 'Comments', 'Memo'],
    sheetHints: ['Notes'],
    type: 'string',
  },
]

export const fieldLabelMap: Record<string, string> = {
  grossPotentialRent: 'Gross Potential Rent (GPR)',
  vacancyLoss: 'Vacancy Loss',
  concessions: 'Concessions',
  badDebt: 'Bad Debt & Credit Loss',
  utilityReimbursements: 'Utility Reimbursements',
  otherIncome: 'Other Income',
  propertyManagementFee: 'Property Management Fee',
  payrollBenefits: 'Payroll & Benefits',
  repairsMaintenance: 'Repairs & Maintenance',
  makeReadyTurns: 'Make-Ready / Unit Turns',
  landscaping: 'Landscaping & Grounds',
  utilitiesCommonArea: 'Utilities — Common Area',
  insurance: 'Insurance',
  propertyTaxes: 'Property Taxes',
  marketingAdvertising: 'Marketing & Advertising',
  administrativeGeneral: 'Administrative & General',
  contractServices: 'Contract Services',
  totalRentableUnits: 'Total Rentable Units',
  occupiedUnits: 'Occupied Units',
  avgRent: 'Average Rent ($/unit/mo)',
  depreciation: 'Depreciation',
  amortizationFinancingCosts: 'Amortization of Deferred Financing Costs',
  debtServiceInterest: 'Debt Service Interest',
  debtServicePrincipal: 'Debt Service Principal',
  capEx: 'Capital Expenditures (CapEx)',
  replacementReserve: 'Replacement Reserve',
  depreciationOverridden: 'Depreciation Overridden',
  debtServiceOverridden: 'Debt Service Overridden',
  capExOverridden: 'CapEx Overridden',
  changeInAccountsReceivable: 'Change in Accounts Receivable',
  changeInPrepaidExpenses: 'Change in Prepaid Expenses',
  changeInAccountsPayable: 'Change in Accounts Payable',
  changeInAccruedLiabilities: 'Change in Accrued Liabilities',
  changeInSecurityDeposits: 'Change in Security Deposits',
  otherOperatingAdjustments: 'Other Operating Adjustments',
  proceedsFromSaleOfAssets: 'Proceeds from Sale of Assets',
  otherInvestingActivities: 'Other Investing Activities',
  proceedsFromNewBorrowings: 'Proceeds from New Borrowings',
  capitalContributions: 'Capital Contributions',
  otherFinancingActivities: 'Other Financing Activities',
  actualLPDistribution: 'Actual LP Distribution',
  actualGPDistribution: 'Actual GP Distribution',
  isOverridden: 'Distribution Override',
  overrideNote: 'Override Note',
  notes: 'Notes',
}