export type BlueSkyStateRule = {
  stateCode: string
  stateName: string
  requiresFormDNoticeFiling: boolean
  newNoticeFee: string
  feeType: string
  variableCalculation: string
  hasRenewalOrAnnualSalesReportFee: boolean
  lateFee: string
  amendmentNoticeFee: string
  renewalOrAnnualSalesReportFee: string
  renewalLateFee: string
  terminationFee: string
  withdrawalFee: string
}

// Baseline dataset provided by user (Rule 506/Form D, NASAA EFD fee schedule as of 2026-01-01).
// Always validate state-specific requirements with legal/compliance counsel before filing.
export const BLUE_SKY_RULE_506_BY_STATE: Record<string, BlueSkyStateRule> = {
  AL: {
    stateCode: 'AL',
    stateName: 'Alabama',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$300',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  AK: {
    stateCode: 'AK',
    stateName: 'Alaska',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$600',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: true,
    lateFee: '$600',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  AZ: {
    stateCode: 'AZ',
    stateName: 'Arizona',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$250',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  AR: {
    stateCode: 'AR',
    stateName: 'Arkansas',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$100 minimum; variable .1% of state offering max $500',
    feeType: 'Fixed & Variable',
    variableCalculation: '.1% of state offering; min $100 max $500',
    hasRenewalOrAnnualSalesReportFee: true,
    lateFee: '$500 >15 days after first sale in state; $1,000 >365 days',
    amendmentNoticeFee: '.001 of state offering; min $100, max $500',
    renewalOrAnnualSalesReportFee: '$100',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  CA: {
    stateCode: 'CA',
    stateName: 'California',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$300',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  CO: {
    stateCode: 'CO',
    stateName: 'Colorado',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$50',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  CT: {
    stateCode: 'CT',
    stateName: 'Connecticut',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$150',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  DE: {
    stateCode: 'DE',
    stateName: 'Delaware',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$200 minimum; variable .5% of state offering max $1,000',
    feeType: 'Variable',
    variableCalculation: '.5% of state offering max $1,000',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '>15 days after first sale in state: .5% of state offering amount max $1,000',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  FL: {
    stateCode: 'FL',
    stateName: 'Florida',
    requiresFormDNoticeFiling: false,
    newNoticeFee: '',
    feeType: '',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'Not listed in Form D fee matrix; state marked as not requiring a Form D filing',
    amendmentNoticeFee: '',
    renewalOrAnnualSalesReportFee: '',
    renewalLateFee: '',
    terminationFee: '',
    withdrawalFee: '',
  },
  GA: {
    stateCode: 'GA',
    stateName: 'Georgia',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$250 + $10 processing fee',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: '$100 + $10 processing fee',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  HI: {
    stateCode: 'HI',
    stateName: 'Hawaii',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$100',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  ID: {
    stateCode: 'ID',
    stateName: 'Idaho',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$50',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  IL: {
    stateCode: 'IL',
    stateName: 'Illinois',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$100',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: '$100',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  IN: {
    stateCode: 'IN',
    stateName: 'Indiana',
    requiresFormDNoticeFiling: true,
    newNoticeFee: 'No Fee',
    feeType: 'N/A',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  IA: {
    stateCode: 'IA',
    stateName: 'Iowa',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$100',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '$250 >15 days after the first sale in state',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  KS: {
    stateCode: 'KS',
    stateName: 'Kansas',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$0',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '$0',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  KY: {
    stateCode: 'KY',
    stateName: 'Kentucky',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$250',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  LA: {
    stateCode: 'LA',
    stateName: 'Louisiana',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$300',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  ME: {
    stateCode: 'ME',
    stateName: 'Maine',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$300',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '$500 >15 days after the first sale in state',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  MD: {
    stateCode: 'MD',
    stateName: 'Maryland',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$100',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '$150 >15 days after first sale in state',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  MA: {
    stateCode: 'MA',
    stateName: 'Massachusetts',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$250-$750',
    feeType: 'Variable',
    variableCalculation: 'EDGAR offering up to $2M: $250; $2,000,000.01-$7,500,000: $500; $7,500,000.01+: $750',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  MI: {
    stateCode: 'MI',
    stateName: 'Michigan',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$100',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  MN: {
    stateCode: 'MN',
    stateName: 'Minnesota',
    requiresFormDNoticeFiling: true,
    newNoticeFee: 'Fixed $100 + variable .1% of state offering max $200; max combined $300',
    feeType: 'Fixed & Variable',
    variableCalculation: '$100 plus .1% of state offering max $200; max combined $300',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: '.1% of increase in offering; max $199',
    renewalOrAnnualSalesReportFee: '.1% of increase in offering; max $199',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  MS: {
    stateCode: 'MS',
    stateName: 'Mississippi',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$300',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: true,
    lateFee: '>15 days: 1% of state sold amount; max $5,000',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: '$300',
    renewalLateFee: 'No',
    terminationFee: '$50',
    withdrawalFee: '$50',
  },
  MO: {
    stateCode: 'MO',
    stateName: 'Missouri',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$100',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '$50 >15 days after date of first sale',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  MT: {
    stateCode: 'MT',
    stateName: 'Montana',
    requiresFormDNoticeFiling: true,
    newNoticeFee: 'Fixed $200; variable .1% > $100,000 max combined $1,000',
    feeType: 'Fixed & Variable',
    variableCalculation: 'If state offering < $100,001, fixed $200; if > $100,000, $200 plus .001 of average, max $800',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: '.1% > $100,000 max $800',
    renewalOrAnnualSalesReportFee: 'Fixed $200 + variable .1% $100,000 max combined $1,000',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  NE: {
    stateCode: 'NE',
    stateName: 'Nebraska',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$200',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '$200 >15 days after the date of first sale',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  NV: {
    stateCode: 'NV',
    stateName: 'Nevada',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$500',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: true,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: '$500',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  NH: {
    stateCode: 'NH',
    stateName: 'New Hampshire',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$500',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '$500 16-90 days; $1,000 91-365 days',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  NJ: {
    stateCode: 'NJ',
    stateName: 'New Jersey',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$750',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  NM: {
    stateCode: 'NM',
    stateName: 'New Mexico',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$350',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '$700 16-25 days; $1,050 >25 days',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  NY: {
    stateCode: 'NY',
    stateName: 'New York',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$300-$1,200',
    feeType: 'Variable',
    variableCalculation: '$300 for EDGAR offering amounts $0-$500,000; $1,200 for $500,001+; fees tied to issuer CIK and not individual Form D. $30 for no-variable-fee filings within effectiveness period.',
    hasRenewalOrAnnualSalesReportFee: true,
    lateFee: 'No',
    amendmentNoticeFee: '$30',
    renewalOrAnnualSalesReportFee: 'Every four years; same as new notice fee ($300-$1,200). Fees tied to issuer CIK and not individual Form D. $30 for no-variable-fee filings within effectiveness period.',
    renewalLateFee: 'No',
    terminationFee: '$30 add $900 if EDGAR offering amount increased from below $500K to $500,001+',
    withdrawalFee: '$30',
  },
  NC: {
    stateCode: 'NC',
    stateName: 'North Carolina',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$350',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  ND: {
    stateCode: 'ND',
    stateName: 'North Dakota',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$100',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: true,
    lateFee: '$250',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: '$100',
    renewalLateFee: '$250',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  OH: {
    stateCode: 'OH',
    stateName: 'Ohio',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$100',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '$100 >15 days after the date of first sale',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  OK: {
    stateCode: 'OK',
    stateName: 'Oklahoma',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$250',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '$250',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  OR: {
    stateCode: 'OR',
    stateName: 'Oregon',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$250',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: '$100 for amendment that increases offering amount',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  PA: {
    stateCode: 'PA',
    stateName: 'Pennsylvania',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$525',
    feeType: 'Variable',
    variableCalculation: 'For multi-issuer filings, a Form D notice and the $525 fee must be submitted for each issuer.',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  RI: {
    stateCode: 'RI',
    stateName: 'Rhode Island',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$300',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  SC: {
    stateCode: 'SC',
    stateName: 'South Carolina',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$300',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: true,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: '$300',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  SD: {
    stateCode: 'SD',
    stateName: 'South Dakota',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$250',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '$275 >15 days after the date of first sale',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  TN: {
    stateCode: 'TN',
    stateName: 'Tennessee',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$500',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: true,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: '$100',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  TX: {
    stateCode: 'TX',
    stateName: 'Texas',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$0-$500',
    feeType: 'Variable',
    variableCalculation: '.1% of EDGAR offering; max $500',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: '.1% of EDGAR offering; max $500',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  UT: {
    stateCode: 'UT',
    stateName: 'Utah',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$0-$100',
    feeType: 'Variable',
    variableCalculation: '$0 for EDGAR offerings up to $500K; $100 for $500,001+',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '$500 >15 days, in lieu of new notice fee',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  VT: {
    stateCode: 'VT',
    stateName: 'Vermont',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$820',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: true,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: '$820',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  VA: {
    stateCode: 'VA',
    stateName: 'Virginia',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$250',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '$250 16-90 days after the date of first sale; $500 91-182 days; $750 >182+ days',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  WA: {
    stateCode: 'WA',
    stateName: 'Washington',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$300',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  WV: {
    stateCode: 'WV',
    stateName: 'West Virginia',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$125',
    feeType: 'Fixed & Variable',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '$420-$1,800 >15 days after first sale in state; .18750% of amount oversold',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  WI: {
    stateCode: 'WI',
    stateName: 'Wisconsin',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$200',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: '$200 >15 days',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
  WY: {
    stateCode: 'WY',
    stateName: 'Wyoming',
    requiresFormDNoticeFiling: true,
    newNoticeFee: '$200',
    feeType: 'Fixed',
    variableCalculation: '',
    hasRenewalOrAnnualSalesReportFee: false,
    lateFee: 'No',
    amendmentNoticeFee: 'No',
    renewalOrAnnualSalesReportFee: 'No',
    renewalLateFee: 'No',
    terminationFee: 'No',
    withdrawalFee: 'No',
  },
}
